spring.application.name=collection-micro-service
server.port=8084

# Jasypt Anahtarı (Güvenli Kasadan)
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}

# Veritabanı Bağlantısı - Aiven MySQL (Sıfır Hardcode)
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/collection_db?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ve Liquibase Ayarları
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# Mikroservisler Arası İletişim (Sıfır Hardcode - Bulut Uyumlu)
application.service.url=${APPLICATION_SERVICE_URL:http://localhost:8083}
policy.service.url=${POLICY_SERVICE_URL:http://localhost:8085}